# numpy类似于python中的列表，他们都可以作为容器有增删改查的功能
# 在一维以上维度是向量化操作比列表快，打在末尾添加元素比列表慢



In [4]:
import numpy as np
# 向量初始化
a=np.array([1.,2.,3.])
a.dtype
a.shape

(3,)

In [5]:
# 用np.zeros和np.empty初始化数组，预分配必要的空间
b=np.zeros(3,int)
b

array([0, 0, 0])

In [6]:
# 创建一个空数组，大小和元素类型与现有数组相同
c=np.zeros_like(a)
c

array([0., 0., 0.])

In [7]:
# 用常量的函数填充基本都有_like
d=np.ones_like(a)
d

array([1., 1., 1.])

In [8]:
d=np.full_like(a,8)
d

array([8., 8., 8.])

In [10]:
# 在npmpy中，可以用arrange或者linspace来初始化单调序列数组
np.arange(6)
np.arange(2,6)
np.arange(1,6,2)

array([1, 3, 5])

In [12]:
np.linspace(0,0.5,7)

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       ])

In [13]:
# 处于测试目的，通常需要生成随机数组，numpy提供随机整数，均匀分布，正态分布，等几种随机数形式：
np.random.randint(0,10,3)

array([9, 4, 7])

In [14]:
np.random.rand(3)

array([0.03408391, 0.22134541, 0.16607491])

In [16]:
np.random.uniform(1,10,3)

array([5.61161279, 8.93700238, 8.54575284])

In [4]:
# 向量索引
# 基础的向量索引操作，只是展示部分数据，而不改变数据本身
import numpy as np
a=np.arange(1,6)
a[0:2]

array([1, 2])

In [9]:
# 布尔操作
a=np.arange(10)
print(np.any(a>5))
print(a[a>5])
print(np.all(a>5))
# 也可用where和clip代替上面的方法
print(np.where(a>5))
print(np.nonzero(a>5))
print(np.where(a>=5,1,0))
print(np.clip(a,3,5))

True
[6 7 8 9]
False
(array([6, 7, 8, 9], dtype=int64),)
(array([6, 7, 8, 9], dtype=int64),)
[0 0 0 0 0 1 1 1 1 1]
[3 3 3 3 4 5 5 5 5 5]


In [ ]:
a=np.array([1,2])
a*2
b=[2,4]
a*b

array([2, 8])

In [12]:
# 二维array，也成matrix矩阵
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.full((3,2),7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [15]:
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# 随机matrix，同一维类似
np.random.randint(0,10,(3,2))

array([[9, 6],
       [2, 1],
       [3, 4]])

In [19]:
np.random.rand(3,2)

array([[0.80095027, 0.31507768],
       [0.24719679, 0.09026454],
       [0.03921669, 0.8694682 ]])

In [20]:
np.random.uniform(1,10,(3,2))

array([[8.92896076, 3.93815275],
       [7.31402038, 9.1875505 ],
       [1.4030084 , 9.07901473]])

In [21]:
np.random.randn(3,2)

array([[-0.58668958,  0.55901999],
       [ 1.7229227 , -0.03596507],
       [-0.337451  ,  1.4982355 ]])

In [22]:
np.random.normal(10,2,(3,2))

array([[11.01791913,  9.10952132],
       [ 8.92558551, 10.0717657 ],
       [13.81124918, 10.7205316 ]])

In [26]:
a=np.random.randint(0,10,(3,4))

In [27]:
a[2,3]

2

In [28]:
a

array([[7, 1, 6, 1],
       [7, 0, 4, 1],
       [5, 2, 9, 2]])

In [29]:
a[:,1:3]

array([[1, 6],
       [0, 4],
       [2, 9]])

In [30]:
a

array([[7, 1, 6, 1],
       [7, 0, 4, 1],
       [5, 2, 9, 2]])

In [33]:
np.delete(a,[1,3],axis=1)

array([[7, 6],
       [7, 4],
       [5, 9]])

In [34]:
a

array([[7, 1, 6, 1],
       [7, 0, 4, 1],
       [5, 2, 9, 2]])

In [36]:
np.insert(a,[1,3],0,axis=1)

array([[7, 0, 1, 6, 0, 1],
       [7, 0, 0, 4, 0, 1],
       [5, 0, 2, 9, 0, 2]])

In [66]:
res = np.append(a, np.ones((1,4)), axis=0)
res

array([[7., 1., 6., 1.],
       [7., 0., 4., 1.],
       [5., 2., 9., 2.],
       [1., 1., 1., 1.]])

In [47]:
a

array([[7, 1, 6, 1],
       [7, 0, 4, 1],
       [5, 2, 9, 2]])